### PR TITLE
uavcan_escs: Add VESC setup information

### PR DESCRIPTION
**Pull request by RicardoM17**
Signed-off-by: Ricardo Marques <marques.ricardo17@gmail.com>

### CODE REVIEW

**Comment by RicardoM17** [comment]
@hamishwillee FYI

**Comment by hamishwillee** [comment]
Thanks @RicardoM17 ! 

1. Does it matter the order that you do things? i.e This says you do normal setup in the VESC tool and also set up the app configuration - but I assume that you're saying first do the app configuration so that the VESC setup works?
2. Is it obvious where the app configuration is? I was looking for a screenshot on google play and there isn't an obvious app config place. It might be worth a screenshot.

**Comment by RicardoM17** [comment]
Hi @hamishwillee both the motor configuration and the app configuration are done in the VESC Tool. For the motor configuration however, no pixhawk is needed for example. In order to run with px4 both need to be done but the order is not that important.

The place for the app configuration in the VESC Tool is quite obvious yes. If needed I can add a screenshot at a later date with a more detailed explanation? Not sure if it’s needed however.

P.s. I saw your subedit but I’ll leave it up to you. Unfortunately the VESC tool is not consistent and it has both Can and CAN. So I left it as it is in the VESC Tool. But either way it’s not a big deal and we can opt to be consistent on our side.

**Comment by hamishwillee** [comment]
@RicardoM17 Thanks - I've reverted the parameter name and merged. If this is pretty much obvious once you're using the app then you've almost certainly hit the right level of detail - i.e. explain what they need to change and the essential params.

**Comment by RicardoM17** [comment]
@hamishwillee No problem @hamishwillee , I'm happy to contribute :) 

I might do a follow up PR with a screenshot of the VESC Tool just to make it complete. It's never enough. And I'll also add a link to purchase VESC from https://trampaboards.com/vesc--c-1434.html , which is the official store for VESC. There are other alternatives but we've had quite a lot of issues with them and lost a ton of time in the process. I don't think those alternatives are appropriate for UAVs. What do you think?

**Comment by hamishwillee** [comment]
>  I don't think those alternatives are appropriate for UAVs. What do you think?

I think that if there is a single great alternative that does the job and is "preferred" we use that. Perhaps just a note like "Other VESC configuration apps exist but these have not be validated/tested. These include (non-exhaustively): 

Yes I know you have tested them, the point is to recommend something good and to let people know the other choices if they want to look further. Don't list any you know are really crap for drones.

Cheers!

**Comment by RicardoM17** [comment]
@hamishwillee my meaning with "what do you think" was mostly on adding the link to this "official" version, which we know works.

FYI I was talking about differente VESC manufacturers, not necessarily new configs (though those exist too).

That being said it does sound like a good idea so expect a PR from me soon with that info ;) 

Have a good weekend.

**Comment by hamishwillee** [comment]
Thanks for the clarification. Yes :-)

**Pull request merged**
