### PR TITLE
Add HKPilot32 SWD link

### PR DESCRIPTION
**Pull request by hamishwillee**
Adds link from HKPilot32 debug port info to 3DR Pixhawk 1 page - they are pretty much the same under the hood.

@davids5 Do you happen to know whether Pixfalcon has an SWD or Serial console interface? If so, do you have any imagery? No worries if not, I will just omit it for now.

### CODE REVIEW

**Comment by davids5** [comment]
@hamishwillee if it is the same as the old 3dr PH mini, then no, neither, you have to solder wires to the board test pads for SWD and IC to a console.

**Comment by hamishwillee** [comment]
@davids5 Thanks. FMI, what does it mean to say " and IC to a console."?

I have added debug port sections to the Pixfalcon and 3DR mini pages stating the port is not present and adding your text above. While it would be nice to add images showing the ports/wiring I figure anyone who wants to do this will be willing to do some digging. Making it clear that this won't be easy is enough to help most users.

**Comment by davids5** [comment]
> @davids5 Thanks. FMI, what does it mean to say " and IC to a console."

Soldering wires on to the STM32F4 (IC) TX and RX to get a console.

**Comment by hamishwillee** [comment]
David - thank you very much for clarification. Merged.

**Pull request merged**
