### PR TITLE
Mc advanced tuning

### PR DESCRIPTION
**Pull request by Stifael**
rendered version:
https://madennis.gitbooks.io/px4user/content/en/advanced_config/advanced_mc_position_tuning.html

As it is.

### CODE REVIEW

**Comment by hamishwillee** [comment]
Thanks @Stifael, you OK if I merge this and do minor edits for wiki style?

**Comment by Stifael** [comment]
@hamishwillee of course. There are also some typos :)

**Comment by hamishwillee** [comment]
Thanks Stifael! Merged. I'll PR my minor updates for you to reflect upon.

@bkueng YOu may wish to review this also. I'm updating for style this afternoon.

**Comment by hamishwillee** [comment]
OK, updates in https://github.com/PX4/px4_user_guide/pull/177

**Pull request merged**
