### PR TITLE
update pixhawk 4 datasheet

### PR DESCRIPTION
**Pull request by pfjare**
Update link to Pixhawk 4 technical data sheet

### CODE REVIEW

**Comment by hamishwillee** [comment]
I think moving the datasheet here is a good idea - but do "we" own the master copy or Holybro? I just want to understand whether there is another version that we should be tracking.

**Comment by pfjare** [comment]
I remade holybros basically so I could make sure the Pixhawk 4 Mini datasheet and the Pixhawk 4 datasheet had a consistent style.

**Comment by hamishwillee** [comment]
Thanks for clarification. Makes perfect sense.

**Comment by pfjare** [comment]
On the live site the link is the same. Do you push changes on a schedule? Jinger is asking me why it hasnt changed

**Comment by dagar** [comment]
> On the live site the link is the same. Do you push changes on a schedule? Jinger is asking me why it hasnt changed

The credentials for PX4BuildBot changed and haven't been updated everywhere yet. I'll have it fixed soon.

**Comment by pfjare** [comment]
Ok thank you

**Pull request merged**
