### PR TITLE
flight_controller_orientation: Include tailsitter config note

### PR DESCRIPTION
**Pull request by RicardoM17**
Closes: https://github.com/PX4/px4_user_guide/issues/615

### CODE REVIEW

**Comment by RicardoM17** [comment]
@hamishwillee FYI

**Comment by hamishwillee** [comment]
@RicardoM17 I can add anyone who is a member of the organisation/docs team as a reviewer; what I don't know is how you get to be part of the org. 
@mrpollo I can't seem to add Ricardo to the docs team - what do I need to in order to add "anyone"? Also who can assign reviewers?

**Comment by hamishwillee** [comment]
@RicardoM17 Thanks. I have done very minor subedit to personal taste. This is a good place for the info. I wish that we had a collection of docs on VTOL setup/calibration for various types of VTOL as that would be an even better place. Oh well.

**Comment by RicardoM17** [comment]
@hamishwillee what I meant was that in some repos anyone (even without being part of the organization) can add maintainers to the reviewers list, without having to @ them in the comments. This just makes it easier to alert someone imo.

regarding being a part of the docs team if that's something that you feel like it then I wouldn't say no. I'm just happy to help :)

Regarding the VTOL not sure what is missing specifically. Depending on that perhaps I could include a thing or two more.

**Comment by hamishwillee** [comment]
@RicardoM17 Do you know where that setting is to allow that? I don't think I have necessary rights.

**Comment by mrpollo** [comment]
@hamishwillee I just added @RicardoM17 to the docs team! sorry for the delay, notifications are getting out of hand

**Comment by hamishwillee** [comment]
Thanks @mrpollo - I know how you feel! Would be good if I could have this right too - for the docs team?

**Pull request merged**
