### PR TITLE
Tidy up docs around aero/leddar1

### PR DESCRIPTION
**Pull request by hamishwillee**
This tidies up the docs added in https://github.com/PX4/px4_user_guide/pull/215 to improve English and cross link to related information.

### CODE REVIEW

**Comment by zehortigoza** [comment]
LGTM, thanks for the improvements =D

**Comment by hamishwillee** [comment]
@zehortigoza Awesome. 

The actual docs on Aero look good now, but the other ones about Leddar1 now appear to be out of date. Specifically current rangefinder docs indicate that LeddarOne is not in firmware by default and you need to start manually.  The [SENS_EN_LEDDAR1](https://docs.px4.io/en/advanced_config/parameter_reference.html#SENS_EN_LEDDAR1) is "new" .

Is it in firmware now by default?

Looking at 
https://github.com/PX4/Firmware/blob/master/ROMFS/px4fmu_common/init.d/rc.sensors#L421
- Sensor enabled automatically on PX4FMU_V2 PX4FMU_V4PRO on serial 4/5
- Sensor enabled for Aero on TELEMETRY port
- For other hardware is started on TELEM2

Is that correct? If so, I'll update that and then merge.

**Comment by zehortigoza** [comment]
Not all boards have it, you can check here the ones that have: https://github.com/PX4/Firmware/search?utf8=%E2%9C%93&q=%22drivers%2Fdistance_sensor%22 all the ones that includes "drivers/distance_sensor".
And yes, most of the boards have the telemetry in ttyS2 so SENS_EN_LEDDAR1=1 would be enough to start it.

**Comment by hamishwillee** [comment]
Thanks @zehortigoza 

I'll merge this and fix up the leddar1 doc separately.

**Comment by hamishwillee** [comment]
... which you can now see in https://github.com/PX4/px4_user_guide/pull/217 - would appreciate your review :-)

**Pull request merged**
