### PR TITLE
Add S500 V2 Buildlog

### PR DESCRIPTION
**Pull request by Junkim3DR**
Full build log of S500 V2 frame with Pixhawk4 v5 autopilot.

### CODE REVIEW

**Comment by Junkim3DR** [comment]
Pending to add images, haven't been able to figure out the process.

**Comment by hamishwillee** [comment]
You can only add images using the git toolchain. They get copied into a subfolder of **/assets** and referenced like:
```
![My image description](../../assets/path_to_file/filename)
```
Note the *../../* on the path - that is because the assets folder is two directories down with respect to any doc file.

Note also that this will not build in gitbook yet as you need to add a link to the new doc in **en/SUMMARY.md**.

I have updated the instructions on the doc structure here: https://github.com/PX4/Devguide/blob/master/en/contribute/docs.md#source-code-structure (not built live yet)

Sufficient?

**Comment by mrpollo** [comment]
Can we push this one through, whats missing here?

**Comment by hamishwillee** [comment]
Images have been provided but not yet integrated. This also hasn't been added to SUMMARY.md. I have not reviewed it.

**Comment by mrpollo** [comment]
Closed in favor of #682

**Pull request closed without merging**
