### PR TITLE
/px4_user_guide/ko/config/README.md translated into Korean

### PR DESCRIPTION
**Pull request by korkeep**
/px4_user_guide/ko/config/README.md translated into Korean

I have corrected some errors in the translated results.
I will continue fixing the translation errors.

### CODE REVIEW

**Comment by Jaeyoung-Lim** [comment]
@korkeep Did you manually edit the changes? or is this coming from crowdin?

**Comment by korkeep** [comment]
> @korkeep Did you manually edit the changes? or is this coming from crowdin?

I manually edited those changes :)
This is my first experience participating in an open source translation project, are there any rules I should follow? :(

**Comment by Jaeyoung-Lim** [comment]
@korkeep There are no rules, and I appreciate you doing this. We need more people in the korean translation team.

In case of korean translation, we use a tool called [Crowdin](https://crowdin.com/project/px4-user-guide) so we can manage automatically the changes that are done in upstream master. Those changes are automatically merged into the docs.

**Comment by korkeep** [comment]
I made registration request for Crowdin translation team. Thanks for a detailed explanation :)

**Comment by korkeep** [comment]
> @korkeep There are no rules, and I appreciate you doing this. We need more people in the korean translation team.
> 
> In case of korean translation, we use a tool called [Crowdin](https://crowdin.com/project/px4-user-guide) so we can manage automatically the changes that are done in upstream master. Those changes are automatically merged into the docs.

I made registration request for Crowdin translation team. Thanks for a detailed explanation :)

**Comment by Jaeyoung-Lim** [comment]
@korkeep Did you get accepted? I couldn't see the request

**Comment by korkeep** [comment]
capture
@Jaeyoung-Lim The pop-up says I have not been approved yet. Could you check once again please?

**Comment by Jaeyoung-Lim** [comment]
@korkeep Right, I don't seem to have access. @hamishwillee Can I get proofreader access?

**Comment by hslyu** [comment]
I will check your translation and approve it. Thank you for your contribution!

**Comment by korkeep** [comment]
@Jaeyoung-Lim @hslyu Thank you for checking. As it is my first translation project, I will do my best :)

**Comment by Jaeyoung-Lim** [comment]
@korkeep Did you manage to get access to crowdin?

**Comment by hslyu** [comment]
@Jaeyoung-Lim @korkeep I got no request on Crowdin yet

**Comment by korkeep** [comment]
@Jaeyoung-Lim @hslyu  I have not been approved yet :(

**Comment by hslyu** [comment]
Use (Crowdin)[https://crowdin.com/project/px4-user-guide] instead of translating directly from github. We approve one of the participants' "candidate" translations. Therefore, your translations may not be approved. By the way, I can't find your translations on crowdin website. Could you specify how you request the approval of your translation?

**Comment by korkeep** [comment]
@hslyu https://crowdin.com/project/px4-user-guide/ko#
I visited upper URL and clicked "Join" button. Is there anything I did wrong?

**Comment by hamishwillee** [comment]
@korkeep Welcome! I've accepted your request to join on Crowdin. It is the weekend where I am located, so had not yet seen the notification.

@Jaeyoung-Lim I've made you proofreader. Please checkit worked :-)

@hslyu Thanks for following up on this. Great to see the Korean translation evolving so quickly.

I'll close this now.

**Comment by Jaeyoung-Lim** [comment]
@hamishwillee Thanks!

**Pull request closed without merging**
