### PR TITLE
Add S500 V2 Buildlog

### PR DESCRIPTION
**Pull request by Junkim3DR**
Full build log of S500 V2 frame with Pixhawk4 v5 autopilot.

### CODE REVIEW

**Comment by hamishwillee** [comment]
This file won't work - the content is markdown, but it is just a random file in the root of the system taht does not even have the file extension .md. 
If you look at the repo you can see that all the other files are organised in sensible locations. For example this file should probably be named/located at `en/frames_multicopter/holybro_s500_v2_pixhawk4_mini.md`. Basically you would copy the file like https://github.com/PX4/px4_user_guide/blob/master/en/frames_multicopter/holybro_qav250_pixhawk4_mini.md and modify it as needed. 
Images should be in `../../assets/airframes/multicopter/holybro_s500_v2_pixhawk4_mini/Your_image.jpg`.

The easiest way to manage this is to clone the repository locally and work in that. If you want you can also build and test it. Lots of info on how to do that in https://dev.px4.io/master/en/contribute/docs.html#gitbook-documentation-toolchain

Cheers

**Comment by hamishwillee** [comment]
Howdy, how is this going @Junkim3DR ?

**Comment by Junkim3DR** [comment]
> Howdy, how is this going @Junkim3DR ?

Hi @hamishwillee, it is a work in progress.
Will start working on this form now on, I've been focused on flying PR's lately.

**Comment by Junkim3DR** [comment]
Created a new PR for the new file created at en/frames_multicopter/holybro_s500_v2_pixhawk4_mini.md

https://github.com/PX4/px4_user_guide/pull/638

**Comment by mrpollo** [comment]
Closed in favor of #638

**Pull request closed without merging**
