### PR TITLE
Move Intel Aero to Complete Vehicles in SUMMARY.md

### PR DESCRIPTION
**Pull request by bys1123**

### CODE REVIEW

**Comment by hamishwillee** [comment]
This is actually a weird one. Yes it is a complete vehicle, but it is also a) discontinued  b) a reference platform, c) treated as an autopilot from a PX4 codebase point of view. 

I'm happy enough to move if no one particularly cares, but this arguable. @bkueng ?

**Comment by bkueng** [comment]
Yes it is a combination of all. But as it's discontinued I would not move it.
@bys1123 do you know of people still using it?

**Comment by bys1123** [comment]
@bkueng people compare the specifications with new stuffs in the market.

**Comment by hamishwillee** [comment]
I wouldn't have made the change, but I don't feel strongly enough to object. Thanks @bys1123

**Pull request merged**
